# -------------------
# Jekyll Config
# --------------------
baseurl: ""
url: ""
permalink: pretty
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page/:num"

# Collections
collections_dir: collections
collections:
  projects:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

# Pages
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml


# -------------------
# Theme Config
# --------------------
title: "Jekyll Curate"
category_dir: category

colors:
  #light-mode colors
  primary_bg: "#0d042b"
  primary_bg_2: "#0d042b"
  primary_bg_3: "#0d042b"
  primary_text: "#fdfcf9"
  base_bg: "#fdfcf9"
  base_bg_2: "#f7f6ed"
  base_bg_3: "#faebd7"
  base_text: "#0d042b"
  base_text_2: "#3b364c"
  logo_text: "#0d042b"
  header_text: "#0d042b"

  # dark-mode colors
  primary_bg_dark: "#fdfcf9"
  primary_bg_2_dark: "#fdfcf9"
  primary_bg_3_dark: "#fdfcf9"
  primary_text_dark: "#1c1c1c"
  base_bg_dark: "#1c1c1c"
  base_bg_2_dark: "#303030"
  base_bg_3_dark: "#575659"
  base_text_dark: "#f5f5f5"
  base_text_2_dark: "#aaabad"
  logo_text_dark: "#fdfcf9"
  header_text_dark: "#fdfcf9"

fonts:
  use_google_fonts: false
  google_fonts_url: "https://fonts.googleapis.com/css2?family=DM+Sans:opsz,wght@9..40,300;9..40,500;9..40,700&family=Fira+Mono&display=swap"
  use_self_hosted_fonts: true # font files must be placed in /assets/fonts folder and the @font-face definitions must be added to /assets/css/fonts.css
  heading: "'DM Sans'"
  base: "'DM Sans'"
  monospace: "'Fira Mono'"
  logo: "'DM Sans'"

logo:
  logo_text: "Zac Schubert-Youston"
  logo_image: assets/images/logo/logo.png
  logo_image_mobile: assets/images/logo/logo-mobile.png
  logo_image_invert: assets/images/logo/logo-invert.png
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.png
  logo_image_desktop_height: "28px"
  logo_image_desktop_width: "28px"
  logo_image_mobile_height: "28px"
  logo_image_mobile_width: "28px"
  show_logo_image_on_mobile: false
  show_logo_image_on_desktop: false
  show_logo_text_on_mobile: true
  show_logo_text_on_desktop: true

header: 
  fixed: false

open_graph:
  meta_opengraph_type: "website"
  meta_twitter_card: "summary"
  meta_twitter_site: "@zerostaticio"
  meta_twitter_creator: "@zerostaticio"

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: true
  show_dark_mode_toggle_in_bottom: false
  show_dark_mode_toggle_in_mobile_menu: true

cookie_banner:
  enabled: true
  show_manage_cookies_at_bottom: true

analytics:
  google_analytics_id: "" # G-XXXXXXXXXX
  gtm_id: "" # GTM-XXXXXXXX
  plausible_data_domain: "" # example: mywebsite.com
  umami_data_website_id: "" # example: "ddd14336-5fb0-4cdd-8f32-e1bfa906cc2b"
  umami_src: "" # "https://analytics.eu.umami.is/script.js"

comments:
  commento:
    enabled: true # you must have a commento account and be on the correct domain. does not work locally.
  disqus:
    shortname: "" # Your disqus shortcode for example "zerostatic". leave this blank ie "" to disable.



contact_form: 
  use_netlify_form: false
  use_formspree_form: true
  formspree_endpoint: https://formspree.io/f/moqyklqv
  netlify_form_name: "contact"

menu: 
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: false

footer:
  enable_footer: true # show/hide the entire footer
  footer_title: "Zac Schubert-Youston"
  footer_description: "Versatile multimedia creator with a specialization in videography and editing."
  enable_social_media_icons: false
  enable_contact_details: false
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: true
  enable_menu_footer_tertiary: false
  footer_secondary_menu_title: "More"
  footer_tertiary_menu_title: "Other"

bottom:
  enable_bottom: true # show/hide the entire bottom (below the footer)
  enable_bottom_menu: false # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© 2024 Zac Schubert-Youston"
  show_rss_icon: true
